# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  macos: circleci/macos@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  mac-gcc:
    macos:
      xcode: 13.4.1
    environment:
      CC: gcc-12
      CXX: g++-12
    steps:
      - checkout
      - restore_cache:
            key: my-cache
      - run: brew install ninja gcc@12
      - save_cache:
          key: my-cache
          paths:
            - /usr/bin/gcc
      - run:
          working_directory: ~/project
          command: mkdir build
      - run:
          working_directory: ~/project
          command: g++-12 build.cc build_main.cc -o kybuild
      - run:
          working_directory: ~/project
          command: ./kybuild
      - run:
          working_directory: ~/project
          command: ./greet Akhilesh

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - mac-gcc